// Code generated by sdm. DO NOT EDIT.

package example

import (
	"time"
)

type UserPii struct {
	Id    string `gorm:"column:id;primaryKey"`
	Name  string `gorm:"column:name;primaryKey"`
	Email string `gorm:"column:email;primaryKey"`
}

type UserChain struct {
	Key        string    `gorm:"primaryKey;column:key"`
	FieldName  string    `gorm:"primaryKey;column:field_name"`
	Version    int64     `gorm:"primaryKey;column:version;autoIncrement"`
	TxHash     string    `gorm:"column:tx_hash"`
	FieldValue string    `gorm:"column:field_value"`
	CreatedAt  time.Time `gorm:"column:created_at"`
}

type UserView struct {
	Id          string `gorm:"column:id"`
	Name        string `gorm:"column:name"`
	Email       string `gorm:"column:email"`
	HashedEmail string `gorm:"column:hashed_email"`
	Address     string `gorm:"column:address"`
	ChainField  string `gorm:"column:chain_field"`
	TxHash      string `gorm:"column:tx_hash"`
}

func (UserPii) TableName() string   { return "pii_users" }
func (UserChain) TableName() string { return "chain_users" }
func (UserView) TableName() string  { return "users" }
