// Code generated by protoc-gen-sdm. DO NOT EDIT.

package user

import (
	"time"
)

type UserPii struct {
	Id      string `gorm:"column:id;primaryKey"`
	Ssn     int64  `gorm:"column:ssn;primaryKey"`
	Address string `gorm:"column:address;primaryKey"`
}

type UserChain struct {
	Key        string    `gorm:"primaryKey;column:key"`
	FieldName  string    `gorm:"primaryKey;column:field_name"`
	Version    int64     `gorm:"primaryKey;column:version;autoIncrement"`
	TxHash     string    `gorm:"column:tx_hash"`
	FieldValue string    `gorm:"column:field_value"`
	CreatedAt  time.Time `gorm:"column:created_at"`
}

type UserView struct {
	Id            string `gorm:"column:id"`
	Ssn           int64  `gorm:"column:ssn"`
	Address       string `gorm:"column:address"`
	HashedAddress string `gorm:"column:hashed_address"`
	Name          string `gorm:"column:name"`
	TxHash        string `gorm:"column:tx_hash"`
}

func (UserPii) TableName() string   { return "pii_users" }
func (UserChain) TableName() string { return "chain_users" }
func (UserView) TableName() string  { return "users" }
